# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20170426_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlocation',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot_location', to='parking.ParkingLot'),
        ),
    ]
