# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0002_spotlocation_spot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_reservation_date', models.DateField()),
                ('spot_reservation_start_time', models.TimeField()),
                ('spot_reservation_end_time', models.TimeField()),
                ('spot_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_spot', to='parking.SpotLocation')),
            ],
        ),
    ]
