# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotreservation',
            name='spot_reservation_date',
        ),
        migrations.RemoveField(
            model_name='spotreservation',
            name='spot_reservation_end_time',
        ),
        migrations.RemoveField(
            model_name='spotreservation',
            name='spot_reservation_start_time',
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='spot_reservation_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 12, 24, 18, 40073, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotreservation',
            name='spot_reservation_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 12, 24, 32, 221491, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
