# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20170426_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotreservation',
            name='spot_reservation_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotreservation',
            name='spot_reservation_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
